// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EfCore.Data
{
    public partial class Role
    {
        public Role()
        {
            Permission = new HashSet<Permission>();
            SecurityGroup = new HashSet<SecurityGroup>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        public virtual ICollection<Permission> Permission { get; set; }
        public virtual ICollection<SecurityGroup> SecurityGroup { get; set; }
    }
}